# Generated by Django 4.2.16 on 2024-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(blank=True, default='user', help_text='Only letters an digits.', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(blank=True, default='user', help_text='Only letters an digits.', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
