# Generated by Django 4.2.16 on 2024-11-19 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('slug', models.SlugField(blank=True, help_text='Только латинские буквы, цифры, `_`, `-`', primary_key=True, serialize=False, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(blank=True, help_text='Только буквы и цифры', max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Только буквы, цифры и знаки припенания', max_length=150, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Только буквы и цифры', max_length=50, verbose_name='Колонка')),
                ('position', models.SmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.kanban', verbose_name='Доска')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
