# Generated by Django 4.2.16 on 2024-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Только буквы, цифры и знаки припенания', max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='name',
            field=models.CharField(help_text='Только буквы и цифры', max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='slug',
            field=models.SlugField(help_text='Только латинские буквы, цифры, `_`, `-`', primary_key=True, serialize=False, unique=True, verbose_name='Слаг'),
        ),
    ]
