# Generated by Django 4.2.16 on 2024-12-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_alter_kanban_description_alter_kanban_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Только буквы и знаки препинания.', max_length=50, verbose_name='Загаловок')),
                ('body', models.CharField(blank=True, help_text='Только буквы и знаки препинания.', max_length=150, verbose_name='Описание')),
                ('deadline', models.DateTimeField(help_text='Не может быть меньше текущей даты.', verbose_name='Дедлайн')),
                ('board', models.ForeignKey(help_text='Обязательное! Должен быт доской типа канбан.', on_delete=django.db.models.deletion.CASCADE, to='boards.kanban', verbose_name='Доска')),
                ('status', models.ForeignKey(blank=True, default=None, help_text='Должен соотносится с существующей колонкой и доской или быть Null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.column', verbose_name='Статус')),
            ],
        ),
    ]
